apps/emprestimos/urls.py
from django.urls import path
from apps.emprestimos import views

app_name = 'apps.emprestimos'

urlpatterns = [
    path('inserir_emprestimo', views.inserir_emprestimo, name='inserir_emprestimo'),
    path('listar_emprestimos', views.listar_emprestimos, name='listar_emprestimos'),
    path('editar_emprestimo/<int:id>', views.editar_emprestimo, name='editar_emprestimo'),
    path('excluir_emprestimo/<int:id>', views.excluir_emprestimo, name='excluir_emprestimo'),
]

biblioteca/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('index/', include("apps.core.urls")),
    path('alunos/', include('apps.alunos.urls', namespace='alunos')),
    path('livros/', include('apps.livros.urls', namespace='livros')),
    path('emprestimos/', include('apps.emprestimos.urls', namespace='emprestimos')),
    path('admin/', admin.site.urls),
]

aluno/models.py
from django.db import models
from datetime import date

class Aluno(models.Model):
    nome = models.CharField(max_length=100, blank=False, null=False)
    matricula = models.CharField(max_length=20, blank=False, null=False)
    email = models.EmailField(blank=False, null=False)
    telefone = models.CharField(max_length=20, blank=False, null=False)
    data_criacao = models.DateTimeField(auto_now_add=True)
    # Data de última modificação automática
    ultima_modificacao = models.DateTimeField(auto_now=True)
    # Data de um evento específico (padrão pode ser alterado)
    data_evento = models.DateField(default=date.today)


    def __str__(self):
        return self.nome


    class Meta:
        db_table = 'Aluno'
        verbose_name = 'Aluno'
        verbose_name_plural = 'Alunos'
        ordering = ['nome']

emprestimo/models.py
from django.db import models
from aluno.models import Aluno
from livros.models import Livro
from datetime import date

class Emprestimo(models.Model):
    aluno_id = models.ForeignKey(Aluno, verbose_name='Aluno', on_delete=models.CASCADE)
    livro_id = models.ForeignKey(Livro, verbose_name='Livro',on_delete=models.CASCADE)
    data_emprestimo = models.DateTimeField(verbose_name='Data Empréstimo', auto_now_add=True)
    data_devolucao = models.DateField(verbose_name='Data Devolução', default=date.today)
    data_prevista_devolucao = models.DateField(verbose_name='Previsão devolução', default=date.today)
    status = models.CharField(max_length=1, choices=[('E','Emprestado'), ('D','Devolvido')])

    def __str__(self):
        return self.status

    class Meta:
        db_table = 'Emprestimo'
        verbose_name = 'Emprestimo'
        verbose_name_plural = 'Emprestimos'
        ordering = ['status']
        managed = True

livros/models.py
from django.db import models

class Livro(models.Model):
    titulo = models.CharField(max_length=100, blank=False, null=False)
    autor = models.CharField(max_length=100, blank=False, null=False)
    edicao = models.CharField(max_length=2)
    editora = models.CharField(max_length=50)
    ano_publicacao = models.DateField(blank=False, null=False)
    isbn = models.CharField(max_length=14)
    numero_paginas = models.IntegerField(blank=False, null=False)


    def __str__(self):
        return self.titulo


    class Meta:
        db_table = 'Livro'
        verbose_name = 'Livro'
        verbose_name_plural = 'Livros'
        ordering = ['titulo']
from django.db import models

# Create your models here.

apps/emprestimos/forms.py
from django import forms
from django.forms import ModelForm, DateInput

from apps.emprestimos.models import Emprestimo

class EmprestimoForm(forms.ModelForm):
    class Meta:
        model = Emprestimo
        exclude = ('data_emprestimo',)
        fields = '__all__'

        widgets = {
            'data_devolucao': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={'type': 'date'}
            ),

            'data_prevista_devolucao': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={'type': 'date'}
            ),
        }

aluno/views.py
from django.shortcuts import render

# Create your views here.

apps/emprestimos/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.shortcuts import render, redirect, get_object_or_404
from apps.emprestimos.forms import EmprestimoForm
from apps.emprestimos.models import Emprestimo


def inserir_emprestimo(request):
    template_name = 'emprestimos/form_emprestimo.html'
    if request.method == 'POST':
        form = EmprestimoForm(request.POST or None, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'O cadastro de empréstimo foi realizado com sucesso!')
        return redirect('emprestimos:listar_emprestimos')
    form = EmprestimoForm()
    context = {'form': form}
    return render(request, template_name, context)

def listar_emprestimos(request):
    template_name = 'emprestimos/listar_emprestimos.html'
    emprestimos = Emprestimo.objects.all()
    context = {'relacao_emprestimos': emprestimos}
    return render(request, template_name, context)

def editar_emprestimo(request, id):
    template_name = 'emprestimos/form_emprestimo.html'
    emprestimo = get_object_or_404(Emprestimo, id=id)
    form = EmprestimoForm(request.POST or None, request.FILES or None, instance=emprestimo)
    context = {'form': form}
    if form.is_valid():
        form.save()
        messages.success(request, 'Os dados foram atualizados com sucesso.')
        return redirect('emprestimos:listar_emprestimos')
    return render(request, template_name, context)

def excluir_emprestimo(request, id):
    template_name = 'emprestimos/excluir_emprestimo.html'
    emprestimo = Emprestimo.objects.get(id=id)
    context = {'emprestimo': emprestimo}
    if request.method == "POST":
        emprestimo.delete()
        messages.error(request, 'O emprestimo foi excluído com sucesso.')
        return redirect('emprestimos:listar_emprestimos')
    return render(request, template_name, context)

emprestimo/views.py
from django.shortcuts import render

# Create your views here.

livros/views.py
from django.shortcuts import render

# Create your views here.

apps/emprestimos/templates/emprestimos/excluir_emprestimo.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Title</title>


    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<div class="card">
    <div class="card-header">
        Tem certeza que deseja remover o aluno abaixo?
    </div>
    <div class="card-body">
        <h5 class="card-title">Id: {{emprestimo.id}}</h5>
        <h5 class="card-title">Aluno: {{emprestimo.aluno_id}}</h5>
        <h5 class="card-title">Livro: {{emprestimo.livro_id}}</h5>
        <h5 class="card-title">Data da devolução: {{emprestimo.data_devolucao}}</h5>
        <h5 class="card-title">Data prev. da Devolução: {{emprestimo.data_prevista_devolucao}}</h5>
        <h5 class="card-title">Status: {{emprestimo.get_status_display}}</h5>

        <form method="post">
             {% csrf_token %}
            <button class="btn btn-danger" type="submit">Remover</button>
            <a href="{{request.META.HTTP_REFERER}}" class="btn btn-primary">Voltar</a>
        </form>
    </div>
</div>
</body>
</html>

apps/emprestimos/templates/emprestimos/excluir_emprestimos.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Excluir Emprestimo</title>


    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<div class="card">
    <div class="card-header">
        Tem certeza que deseja remover o emprestimo abaixo?
    </div>
    <div class="card-body">
        <h5 class="card-title">Id: {{emprestimo.id}}</h5>
        <h5 class="card-title">Título: {{emprestimo.titulo}}</h5>
        <h5 class="card-title">Autor: {{emprestimo.autor}}</h5>
        <h5 class="card-title">Edição: {{livro.edicao}}</h5>
        <h5 class="card-title">Editora: {{livro.editora}}</h5>
        <h5 class="card-title">Ano da Publicação: {{livro.ano_publicacao}}</h5>
        <h5 class="card-title">ISBN: {{livro.isbn}}</h5>
        <h5 class="card-title">Número de Páginas: {{livro.numero_paginas}}</h5>

        <form method="post">
             {% csrf_token %}
            <button class="btn btn-danger" type="submit">Remover</button>
            <a href="{{request.META.HTTP_REFERER}}" class="btn btn-primary">Voltar</a>
        </form>
    </div>
</div>
</body>
</html>

apps/emprestimos/templates/emprestimos/form_emprestimo.html
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cadastro de Empréstimos</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <div class="row">
        <div class="col-12"></div>
    </div>
    <div class="card">
        <div class="card-header">
            <h2><i class="fa fa-users"></i> Cadastro de Empréstimos</h2>
            {% include 'partials/messages.html' %}
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="container">
                    <div class="p-1 mb-2 bg-light text-dark">
                        <div class="form-row">
                            <div class="col-md-5">
                                {{ form.aluno_id.errors }}
                                <label><strong>Aluno: </strong></label>
                                {{ form.aluno_id|add_class:"form-control" }}
                            </div>
                            <div class="col-md-7">
                                {{ form.livro_id.errors }}
                                <label><strong>Livro: </strong></label>
                                {{ form.livro_id|add_class:'form-control' }}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="container">
                    <div class="p-1 mb-2 bg-light text-dark">
                        <div class="form-row">
                            <div class="col-md-4 mb-0">
                                {{ form.data_devolucao.errors }}
                                <label><strong>Data Devolução:</strong></label>
                                {{ form.data_devolucao|add_class:'form-control'  }}
                            </div>
                            <div class="col-md-4">
                                {{ form.data_prevista_devolucao.erros }}
                                <label><strong>Data Prev. Devolução:</strong></label>
                                {{ form.data_prevista_devolucao|add_class:'form-control' }}
                            </div>
                            <div class="col-md-4">
                                {{ form.status.erros }}
                                <label><strong>Status:</strong></label>
                                {{ form.status|add_class:'form-control' }}
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                <div class="container">
                    <div class="p-1 mb-2 bg-light text-dark">
                        <div class="form-row">
                            <div class="col-md-12">
                               <button type="submit" class="btn btn-success">Salvar</button>
                               <a href="{{request.META.HTTP_REFERER}}" class="btn btn-primary">Voltar</a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" ></script>
</body>
</html>

apps/emprestimos/templates/emprestimos/form_emprestimos.html
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cadastro de Empréstimos</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <div class="row">
        <div class="col-12"></div>
    </div>
    <div class="card">
        <div class="card-header">
            <h2><i class="fa fa-users"></i> Cadastro de Empréstimos</h2>
            {% include 'partials/messages.html' %}
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="container">
                    <div class="p-1 mb-2 bg-light text-dark">
                        <div class="form-row">
                            <div class="col-md-8">
                                {{ form.aluno_id.errors }}
                                <label><strong>Aluno: </strong></label>
                                {{ form.aluno_id|add_class:"form-control" }}
                            </div>
                            <div class="col-md-4">
                                {{ form.livro_id.errors }}
                                <label><strong>Livro: </strong></label>
                                {{ form.livro_id|add_class:'form-control' }}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="container">
                    <div class="p-1 mb-2 bg-light text-dark">
                        <div class="form-row">
                            <div class="col-md-4 mb-0">
                                {{ form.data_emprestimo.errors }}
                                <label><strong>Data:</strong></label>
                                {{ form.data_emprestimo|add_class:'form-control'  }}
                            </div>
                            <div class="col-md-4 mb-0">
                                {{ form.data_devolucao.errors }}
                                <label><strong>Data Devolução:</strong></label>
                                {{ form.data_devolucao|add_class:'form-control'  }}
                            </div>
                            <div class="col-md-3">
                                {{ form.data_prevista_devolucao.erros }}
                                <label><strong>Data Prev. Devolução:</strong></label>
                                {{ form.data_prevista_devolucao|add_class:'form-control' }}
                            </div>
                            <div class="col-md-3">
                                {{ form.status.erros }}
                                <label><strong>Status:</strong></label>
                                {{ form.status|add_class:'form-control' }}
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                <div class="container">
                    <div class="p-1 mb-2 bg-light text-dark">
                        <div class="form-row">
                            <div class="col-md-12">
                               <button type="submit" class="btn btn-success">Salvar</button>
                               <a href="{{request.META.HTTP_REFERER}}" class="btn btn-primary">Voltar</a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" ></script>
</body>
</html>

apps/emprestimos/templates/emprestimos/listar_emprestimos.html
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Listagem de Emprestimos</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <div class="row">
        <div class="col-12">
        </div>
    </div>
    <div class="card mb-3">
        <div class="card-header">
            <h2><i class="fa fa-list"> Listagem de Emprestimos</i></h2>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Aluno Id</th>
                            <th>Livro Id</th>
                            <th>Data do Emprestimo</th>
                            <th>Data de Devolução</th>
                            <th>Data Prevista de Devolução</th>
			                <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for e in relacao_emprestimos %}
                        <tr>
                            <td>{{ e.id }}</td>
                            <td><a href="#">{{ e.aluno_id}}</a></td>
                            <td>{{ e.livro_id }}</td>
                            <td>{{ e.data_emprestimo | date:'d/m/Y'}}</td>
                            <td>{{ e.data_devolucao | date:'d/m/Y'}}</td>
                            <td>{{ e.data_prevista_devolucao | date:'d/m/Y'}}</td>
                            {% if e.status == 'E' %}
                            <td><span class="badge badge-danger">{{ e.get_status_display }}</span><td>
                            {% else %}
                            <td><span class="badge badge-success">{{ e.get_status_display }}</span><td>
                            {% endif %}

                                <a href="#">
                                    <i class="fa fa-search" aria-hidden="true" style="color: blue;"></i>
                                </a>
                                <a href= "{% url 'emprestimos:editar_emprestimo' e.id %}">
                                    <i class="fa fa-pencil-square" aria-hidden="true" style="color: #6B8E23;"></i>
                                </a>
                                <a href="{% url 'emprestimos:excluir_emprestimo' e.id %}">
                                    <i class="fa fa-trash" aria-hidden="true" style="color: red;"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-12 card mb-3">
        <div class="card-header">
            <a href="{% url 'emprestimos:inserir_emprestimo' %}"><button class="btn btn-success">Cadastrar</button></a>
        </div>
    </div>
</body>
</html>